### ISSUE TITLE
[feature request] Sync mode, or activate Editor when list item is activated 

### ISSUE THREAD

**Issue by paulvi** [dbickley/OpenEditors#14] opened 2018-04-27 15:23 UTC
Sync mode, or activate Editor when list item is activated

**Comment by dbickley** [comment] 2018-04-27 21:12
Not sure I understand exactly what you mean by this.

**Comment by paulvi** [comment] 2018-04-28 05:42
a new mode, when activated:  
When user clicks once on a list item, the corresponding file Editor goes to top.


in current (default mode),  
user needs to double click to bring up that file Editor.

**Comment by achimmihca** [comment] 2019-05-26 11:35
Not sure if I understand correctly. Do you want to open files with a single click instead double click?
If so, then this is a duplicate of #20

**Closed as completed** 2019-10-26 11:12 UTC
